<a href="https://colab.research.google.com/github/kvarun2300/Aviation/blob/main/Flights.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [32]:
df = pd.read_csv("/content/sample_data/flights.csv", low_memory=False)

In [11]:
df.shape

(5819079, 31)

In [13]:
df.duplicated().sum()

np.int64(0)

In [15]:

cols_to_fill = [
    "DEPARTURE_TIME",
    "DEPARTURE_DELAY",
    "TAXI_OUT",
    "WHEELS_OFF",
    "ELAPSED_TIME",
    "AIR_TIME",
    "WHEELS_ON",
    "TAXI_IN",
    "ARRIVAL_TIME",
    "ARRIVAL_DELAY"
]

df.loc[df["CANCELLED"] == 1, cols_to_fill] = pd.NA

In [22]:
df.head(40)

,YEAR,MONTH,DAY,DAY_OF_WEEK,AIRLINE,FLIGHT_NUMBER,TAIL_NUMBER,ORIGIN_AIRPORT,DESTINATION_AIRPORT,SCHEDULED_DEPARTURE,...,ARRIVAL_TIME,ARRIVAL_DELAY,DIVERTED,CANCELLED,CANCELLATION_REASON,AIR_SYSTEM_DELAY,SECURITY_DELAY,AIRLINE_DELAY,LATE_AIRCRAFT_DELAY,WEATHER_DELAY
0,2015,1,1,4,AS,98,N407AS,ANC,SEA,5,...,408.0,-22.0,0,0,<NA>,NaN,NaN,NaN,NaN,NaN
1,2015,1,1,4,AA,2336,N3KUAA,LAX,PBI,10,...,741.0,-9.0,0,0,<NA>,NaN,NaN,NaN,NaN,NaN
2,2015,1,1,4,US,840,N171US,SFO,CLT,20,...,811.0,5.0,0,0,<NA>,NaN,NaN,NaN,NaN,NaN
3,2015,1,1,4,AA,258,N3HYAA,LAX,MIA,20,...,756.0,-9.0,0,0,<NA>,NaN,NaN,NaN,NaN,NaN
4,2015,1,1,4,AS,135,N527AS,SEA,ANC,25,...,259.0,-21.0,0,0,<NA>,NaN,NaN,NaN,NaN,NaN
5,2015,1,1,4,DL,806,N3730B,SFO,MSP,25,...,610.0,8.0,0,0,<NA>,NaN,NaN,NaN,NaN,NaN
6,2015,1,1,4,NK,612,N635NK,LAS,MSP,25,...,509.0,-17.0,0,0,<NA>,NaN,NaN,NaN,NaN,NaN
7,2015,1,1,4,US,2013,N584UW,LAX,CLT,30,...,753.0,-10.0,0,0,<NA>,NaN,NaN,NaN,NaN,NaN
8,2015,1,1,4,AA,1112,N3LAAA,SFO,DFW,30,...,532.0,-13.0,0,0,<NA>,NaN,NaN,NaN,NaN,NaN
9,2015,1,1,4,DL,1173,N826DN,LAS,ATL,30,...,656.0,-15.0,0,0,<NA>,NaN,NaN,NaN,NaN,NaN
10,2015,1,1,4,DL,2336,N958DN,DEN,ATL,30,...,453.0,-30.0,0,0,<NA>,NaN,NaN,NaN,NaN,NaN
11,2015,1,1,4,AA,1674,N853AA,LAS,MIA,35,...,753.0,-10.0,0,0,<NA>,NaN,NaN,NaN,NaN,NaN
12,2015,1,1,4,DL,1434,N547US,LAX,MSP,35,...,605.0,-4.0,0,0,<NA>,NaN,NaN,NaN,NaN,NaN
13,2015,1,1,4,DL,2324,N3751B,SLC,ATL,40,...,553.0,-22.0,0,0,<NA>,NaN,NaN,NaN,NaN,NaN
14,2015,1,1,4,DL,2440,N651DL,SEA,MSP,40,...,557.0,8.0,0,0,<NA>,NaN,NaN,NaN,NaN,NaN
15,2015,1,1,4,AS,108,N309AS,ANC,SEA,45,...,455.0,-14.0,0,0,<NA>,NaN,NaN,NaN,NaN,NaN
16,2015,1,1,4,DL,1560,N3743H,ANC,SEA,45,...,451.0,-24.0,0,0,<NA>,NaN,NaN,NaN,NaN,NaN
17,2015,1,1,4,UA,1197,N78448,SFO,IAH,48,...,619.0,-7.0,0,0,<NA>,NaN,NaN,NaN,NaN,NaN
18,2015,1,1,4,AS,122,N413AS,ANC,PDX,50,...,507.0,-18.0,0,0,<NA>,NaN,NaN,NaN,NaN,NaN
19,2015,1,1,4,DL,1670,N806DN,PDX,MSP,50,...,551.0,-12.0,0,0,<NA>,NaN,NaN,NaN,NaN,NaN
20,2015,1,1,4,NK,520,N525NK,LAS,MCI,55,...,543.0,6.0,0,0,<NA>,NaN,NaN,NaN,NaN,NaN
21,2015,1,1,4,AA,371,N3GXAA,SEA,MIA,100,...,939.0,1.0,0,0,<NA>,NaN,NaN,NaN,NaN,NaN
22,2015,1,1,4,NK,214,N632NK,LAS,DFW,103,...,529.0,-1.0,0,0,<NA>,NaN,NaN,NaN,NaN,NaN
23,2015,1,1,4,AA,115,N3CTAA,LAX,MIA,105,...,839.0,-12.0,0,0,<NA>,NaN,NaN,NaN,NaN,NaN
24,2015,1,1,4,DL,1450,N671DN,LAS,MSP,105,...,545.0,-23.0,0,0,<NA>,NaN,NaN,NaN,NaN,NaN
25,2015,1,1,4,UA,1545,N76517,LAX,IAH,115,...,607.0,-11.0,0,0,<NA>,NaN,NaN,NaN,NaN,NaN
26,2015,1,1,4,AS,130,N457AS,FAI,SEA,115,...,545.0,-3.0,0,0,<NA>,NaN,NaN,NaN,NaN,NaN
27,2015,1,1,4,NK,597,N528NK,MSP,FLL,115,...,607.0,25.0,0,0,<NA>,25.0,0.0,0.0,0.0,0.0
28,2015,1,1,4,US,413,N571UW,LAS,CLT,120,...,754.0,-31.0,0,0,<NA>,NaN,NaN,NaN,NaN,NaN
29,2015,1,1,4,AA,2392,N3HRAA,DEN,MIA,120,...,709.0,2.0,0,0,<NA>,NaN,NaN,NaN,NaN,NaN
30,2015,1,1,4,NK,168,N629NK,PHX,ORD,125,...,632.0,43.0,0,0,<NA>,43.0,0.0,0.0,0.0,0.0
31,2015,1,1,4,AA,2211,N3CGAA,PHX,MIA,127,...,710.0,-16.0,0,0,<NA>,NaN,NaN,NaN,NaN,NaN
32,2015,1,1,4,AS,136,N431AS,ANC,SEA,135,...,NaN,NaN,0,1,A,NaN,NaN,NaN,NaN,NaN
33,2015,1,1,4,DL,95,N320US,SLC,ATL,140,...,725.0,10.0,0,0,<NA>,NaN,NaN,NaN,NaN,NaN
34,2015,1,1,4,NK,298,N514NK,LAS,IAH,144,...,630.0,-4.0,0,0,<NA>,NaN,NaN,NaN,NaN,NaN
35,2015,1,1,4,HA,17,N389HA,LAS,HNL,145,...,610.0,15.0,0,0,<NA>,0.0,0.0,15.0,0.0,0.0
36,2015,1,1,4,US,617,N804AW,ANC,PHX,152,...,905.0,-10.0,0,0,<NA>,NaN,NaN,NaN,NaN,NaN
37,2015,1,1,4,UA,1528,N76519,SJU,EWR,154,...,458.0,-11.0,0,0,<NA>,NaN,NaN,NaN,NaN,NaN
38,2015,1,1,4,AS,134,N464AS,ANC,SEA,155,...,558.0,-35.0,0,0,<NA>,NaN,NaN,NaN,NaN,NaN
39,2015,1,1,4,B6,304,N607JB,SJU,JFK,155,...,501.0,11.0,0,0,<NA>,NaN,NaN,NaN,NaN,NaN

In [23]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5819079 entries, 0 to 5819078
Data columns (total 31 columns):
 #   Column               Dtype
---  ------               -----
 0   YEAR                 int64
 1   MONTH                int64
 2   DAY                  int64
 3   DAY_OF_WEEK          int64
 4   AIRLINE              object
 5   FLIGHT_NUMBER        int64
 6   TAIL_NUMBER          object
 7   ORIGIN_AIRPORT       object
 8   DESTINATION_AIRPORT  object
 9   SCHEDULED_DEPARTURE  int64
 10  DEPARTURE_TIME       float64
 11  DEPARTURE_DELAY      float64
 12  TAXI_OUT             float64
 13  WHEELS_OFF           float64
 14  SCHEDULED_TIME       float64
 15  ELAPSED_TIME         float64
 16  AIR_TIME             float64
 17  DISTANCE             int64
 18  WHEELS_ON            float64
 19  TAXI_IN              float64
 20  SCHEDULED_ARRIVAL    int64
 21  ARRIVAL_TIME         float64
 22  ARRIVAL_DELAY        float64
 23  DIVERTED             int64
 24  CANCELLED            int64
 25  CANCELLATION_REASON  object
 26  AIR_SYSTEM_DELAY     float64
 27  SECURITY_DELAY       float64
 28  AIRLINE_DELAY        float64
 29  LATE_AIRCRAFT_DELAY  float64
 30  WEATHER_DELAY        float64
dtypes: float64(16), int64(10), object(5)
memory usage: 1.3+ GB

In [24]:
df.isnull().sum()

YEAR                         0
MONTH                        0
DAY                          0
DAY_OF_WEEK                  0
AIRLINE                      0
FLIGHT_NUMBER                0
TAIL_NUMBER              14721
ORIGIN_AIRPORT               0
DESTINATION_AIRPORT          0
SCHEDULED_DEPARTURE          0
DEPARTURE_TIME           89884
DEPARTURE_DELAY          89884
TAXI_OUT                 89884
WHEELS_OFF               89884
SCHEDULED_TIME               6
ELAPSED_TIME            105071
AIR_TIME                105071
DISTANCE                     0
WHEELS_ON                92513
TAXI_IN                  92513
SCHEDULED_ARRIVAL            0
ARRIVAL_TIME             92513
ARRIVAL_DELAY           105071
DIVERTED                     0
CANCELLED                    0
CANCELLATION_REASON    5729195
AIR_SYSTEM_DELAY       4755640
SECURITY_DELAY         4755640
AIRLINE_DELAY          4755640
LATE_AIRCRAFT_DELAY    4755640
WEATHER_DELAY          4755640
dtype: int64

In [21]:
cols = [
    "CANCELLATION_REASON",
    "AIR_SYSTEM_DELAY",
    "SECURITY_DELAY",
    "AIRLINE_DELAY",
    "LATE_AIRCRAFT_DELAY",
    "WEATHER_DELAY"
]

df[cols] = df[cols].fillna(pd.NA)

In [25]:
df = df.fillna("NA")

In [28]:
df.head()

,YEAR,MONTH,DAY,DAY_OF_WEEK,AIRLINE,FLIGHT_NUMBER,TAIL_NUMBER,ORIGIN_AIRPORT,DESTINATION_AIRPORT,SCHEDULED_DEPARTURE,...,ARRIVAL_TIME,ARRIVAL_DELAY,DIVERTED,CANCELLED,CANCELLATION_REASON,AIR_SYSTEM_DELAY,SECURITY_DELAY,AIRLINE_DELAY,LATE_AIRCRAFT_DELAY,WEATHER_DELAY
0,2015,1,1,4,AS,98,N407AS,ANC,SEA,5,...,408.0,-22.0,0,0,NA,NA,NA,NA,NA,NA
1,2015,1,1,4,AA,2336,N3KUAA,LAX,PBI,10,...,741.0,-9.0,0,0,NA,NA,NA,NA,NA,NA
2,2015,1,1,4,US,840,N171US,SFO,CLT,20,...,811.0,5.0,0,0,NA,NA,NA,NA,NA,NA
3,2015,1,1,4,AA,258,N3HYAA,LAX,MIA,20,...,756.0,-9.0,0,0,NA,NA,NA,NA,NA,NA
4,2015,1,1,4,AS,135,N527AS,SEA,ANC,25,...,259.0,-21.0,0,0,NA,NA,NA,NA,NA,NA

In [30]:
df.isnull().sum()

YEAR                   0
MONTH                  0
DAY                    0
DAY_OF_WEEK            0
AIRLINE                0
FLIGHT_NUMBER          0
TAIL_NUMBER            0
ORIGIN_AIRPORT         0
DESTINATION_AIRPORT    0
SCHEDULED_DEPARTURE    0
DEPARTURE_TIME         0
DEPARTURE_DELAY        0
TAXI_OUT               0
WHEELS_OFF             0
SCHEDULED_TIME         0
ELAPSED_TIME           0
AIR_TIME               0
DISTANCE               0
WHEELS_ON              0
TAXI_IN                0
SCHEDULED_ARRIVAL      0
ARRIVAL_TIME           0
ARRIVAL_DELAY          0
DIVERTED               0
CANCELLED              0
CANCELLATION_REASON    0
AIR_SYSTEM_DELAY       0
SECURITY_DELAY         0
AIRLINE_DELAY          0
LATE_AIRCRAFT_DELAY    0
WEATHER_DELAY          0
dtype: int64

In [33]:
df.to_csv('cleaned_data.csv', index=False)
from google.colab import files
files.download('cleaned_data.csv')