<a href="https://colab.research.google.com/github/kvarun2300/Aviation/blob/main/US_Aviation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
df= pd.read_csv('/content/sample_data/flights.csv', low_memory=False)

In [13]:
df.shape

(5332914, 31)

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5819079 entries, 0 to 5819078
Data columns (total 31 columns):
 #   Column               Dtype
---  ------               -----
 0   YEAR                 int64
 1   MONTH                int64
 2   DAY                  int64
 3   DAY_OF_WEEK          int64
 4   AIRLINE              object
 5   FLIGHT_NUMBER        int64
 6   TAIL_NUMBER          object
 7   ORIGIN_AIRPORT       object
 8   DESTINATION_AIRPORT  object
 9   SCHEDULED_DEPARTURE  int64
 10  DEPARTURE_TIME       float64
 11  DEPARTURE_DELAY      float64
 12  TAXI_OUT             float64
 13  WHEELS_OFF           float64
 14  SCHEDULED_TIME       float64
 15  ELAPSED_TIME         float64
 16  AIR_TIME             float64
 17  DISTANCE             int64
 18  WHEELS_ON            float64
 19  TAXI_IN              float64
 20  SCHEDULED_ARRIVAL    int64
 21  ARRIVAL_TIME         float64
 22  ARRIVAL_DELAY        float64
 23  DIVERTED             int64
 24  CANCELLED            int64
 25  CANCELLATION_REASON  object
 26  AIR_SYSTEM_DELAY     float64
 27  SECURITY_DELAY       float64
 28  AIRLINE_DELAY        float64
 29  LATE_AIRCRAFT_DELAY  float64
 30  WEATHER_DELAY        float64
dtypes: float64(16), int64(10), object(5)
memory usage: 1.3+ GB

In [6]:
df = df[df['ORIGIN_AIRPORT'].str.len() <= 3]
df.shape

(5332914, 31)

In [7]:
df.duplicated().sum()

np.int64(0)

In [12]:
df = df[df["ORIGIN_AIRPORT"].str.len() == 3]
df = df[df["DESTINATION_AIRPORT"].str.len() == 3]
print("Remaining rows:", len(df))

Remaining rows: 5332914

In [9]:
cancelled_flights = df['CANCELLED'].sum()
print("cancelled_flights:", cancelled_flights)

cancelled_flights: 87430

In [10]:
cancel_rate = df['CANCELLED'].mean()*100
print("cancel rate:", cancel_rate)

cancel rate: 1.63944140108016

In [15]:
df["CANCELLATION_REASON"].value_counts()

CANCELLATION_REASON
B    47874
A    24309
C    15225
D       22
Name: count, dtype: int64

In [16]:
df['AIRLINE'].value_counts()

AIRLINE
WN    1157339
DL     800329
AA     648694
OO     539545
EV     526249
UA     469829
MQ     272650
B6     245135
US     198715
AS     158054
NK     107171
F9      82735
HA      70030
VX      56439
Name: count, dtype: int64

In [19]:
round(df[df['CANCELLED']==0]['ARRIVAL_DELAY'].mean(),2)

np.float64(4.89)

In [20]:
round(df[df['CANCELLED']==0]['DEPARTURE_DELAY'].mean(),2)

np.float64(9.74)

In [24]:
delay_by_airline= round(df[df['CANCELLED']==0].groupby('AIRLINE')['ARRIVAL_DELAY'].mean(),2)
print("delay by airline:", delay_by_airline)

delay by airline: AIRLINE
AA     3.94
AS    -0.79
B6     6.95
DL     0.68
EV     6.96
F9    13.73
HA     2.16
MQ     7.32
NK    15.21
OO     6.22
UA     6.21
US     3.71
VX     4.98
WN     4.84
Name: ARRIVAL_DELAY, dtype: float64

In [35]:
monthly_flights = df.groupby("MONTH").size()
print(monthly_flights)

MONTH
1     469968
2     429191
3     504312
4     485151
5     496993
6     503897
7     520718
8     510536
9     464946
11    467972
12    479230
dtype: int64

In [26]:
df.shape

(5332914, 31)

In [37]:
df["DAY_OF_WEEK"].value_counts()

DAY_OF_WEEK
1    799248
2    780858
3    790991
4    789594
5    779708
6    637814
7    754701
Name: count, dtype: int64

In [40]:
df["ORIGIN_AIRPORT"].value_counts().head(10)

ORIGIN_AIRPORT
ATL    346836
ORD    285884
DFW    239551
DEN    196055
LAX    194673
SFO    148008
PHX    146815
IAH    146622
LAS    133181
MSP    112117
Name: count, dtype: int64

In [41]:
df["DISTANCE"].describe()

count    5.332914e+06
mean     8.228955e+02
std      6.077992e+02
min      2.100000e+01
25%      3.730000e+02
50%      6.490000e+02
75%      1.065000e+03
max      4.983000e+03
Name: DISTANCE, dtype: float64

In [ ]:
on_time= round(df[df['ARRIVAL_DELAY']<15].mean()*100,2)
print('On Time:', on_time)

Top Airlines with Highest Cancellation Rate

In [10]:
cancel_rate_airline = round(
    df.groupby("AIRLINE")["CANCELLED"]
    .mean()
    .sort_values(ascending=False) * 100,2
)

print(cancel_rate_airline)

AIRLINE
MQ    5.41
EV    2.80
US    2.05
NK    1.81
OO    1.80
B6    1.69
AA    1.57
UA    1.37
WN    1.36
VX    0.91
F9    0.70
DL    0.48
AS    0.40
HA    0.23
Name: CANCELLED, dtype: float64

In [15]:
df.groupby("AIRLINE")['CANCELLED'].value_counts()

AIRLINE  CANCELLED
AA       0             638500
         1              10194
AS       0             157418
         1                636
B6       0             240989
         1               4146
DL       0             796522
         1               3807
EV       0             511495
         1              14754
F9       0              82159
         1                576
HA       0              69871
         1                159
MQ       0             257898
         1              14752
NK       0             105228
         1               1943
OO       0             529826
         1               9719
UA       0             463384
         1               6445
US       0             194648
         1               4067
VX       0              55928
         1                511
WN       0            1141618
         1              15721
Name: count, dtype: int64

Airports with Highest Average Departure Delay

In [16]:
dep_delay_airport = (
    df.groupby("ORIGIN_AIRPORT")["DEPARTURE_DELAY"]
    .mean()
    .sort_values(ascending=False)
    .head(10)
)

print(dep_delay_airport)

ORIGIN_AIRPORT
ILG    29.391753
MVY    25.907317
HYA    23.182927
STC    18.692308
OTH    17.777358
ASE    17.587538
CEC    17.413793
GST    17.171053
BPT    17.020856
GUM    16.647590
Name: DEPARTURE_DELAY, dtype: float64

Airports with Highest Arrival Delay

In [17]:
arr_delay_airport = (
    df.groupby("DESTINATION_AIRPORT")["ARRIVAL_DELAY"]
    .mean()
    .sort_values(ascending=False)
    .head(10)
)

print(arr_delay_airport)

DESTINATION_AIRPORT
STC    23.025974
ILG    21.989474
TTN    17.433901
GUM    17.320242
OTH    16.740602
MQT    16.152027
ASE    15.829448
PBG    15.288256
BPT    14.631694
BQN    12.192771
Name: ARRIVAL_DELAY, dtype: float64

Most Common Flight Routes

In [18]:
df["ROUTE"] = df["ORIGIN_AIRPORT"] + "-" + df["DESTINATION_AIRPORT"]
top_routes = df["ROUTE"].value_counts().head(10)
print(top_routes)

ROUTE
SFO-LAX    13744
LAX-SFO    13457
JFK-LAX    12016
LAX-JFK    12015
LAS-LAX     9715
LGA-ORD     9639
LAX-LAS     9594
ORD-LGA     9575
SFO-JFK     8440
JFK-SFO     8437
Name: count, dtype: int64

Routes with Highest Average Delay

In [19]:
route_delay = (
    df.groupby("ROUTE")["ARRIVAL_DELAY"]
    .mean()
    .sort_values(ascending=False)
    .head(10)
)

print(route_delay)

ROUTE
IAD-TTN    381.00
SWF-PBI    260.50
RIC-CAE    228.00
RDU-IND    208.00
FCA-MSO    148.00
SWF-RSW    140.00
OAK-FLL    106.00
OKC-FLL     90.00
JAC-JFK     89.00
DEN-PIA     84.75
Name: ARRIVAL_DELAY, dtype: float64

Which Day of Week Has Most Delays

In [20]:
delay_by_day = (
    df.groupby("DAY_OF_WEEK")["ARRIVAL_DELAY"]
    .mean()
)

print(delay_by_day)

DAY_OF_WEEK
1    6.740670
2    5.035154
3    4.370272
4    6.257192
5    4.706447
6    2.184446
7    4.370548
Name: ARRIVAL_DELAY, dtype: float64

Month with Highest Cancellation Rate

In [21]:
cancel_month = (
    df.groupby("MONTH")["CANCELLED"]
    .mean() * 100
)

print(cancel_month)

MONTH
1     2.549535
2     4.780389
3     2.181586
4     0.931669
5     1.145690
6     1.809894
7     0.922956
8     0.989548
9     0.446288
11    0.982751
12    1.682491
Name: CANCELLED, dtype: float64

Which Delay Type Contributes Most

In [23]:
delay_types = [
"AIR_SYSTEM_DELAY",
"WEATHER_DELAY",
"AIRLINE_DELAY",
"SECURITY_DELAY",
"LATE_AIRCRAFT_DELAY"
]

df[delay_types].sum().sort_values(ascending=False)

LATE_AIRCRAFT_DELAY    23767674.0
AIRLINE_DELAY          18966945.0
AIR_SYSTEM_DELAY       13533065.0
WEATHER_DELAY           2991008.0
SECURITY_DELAY            77945.0
dtype: float64

In [14]:
df.to_csv('cleaned_data.csv', index=False)
from google.colab import files
files.download('cleaned_data.csv')